### ISSUE TITLE
csv parser error on database

### ISSUE THREAD

**Issue by andrewkern** [shchurch/Insect_Egg_Evolution#1]
Hi there-- I'm hoping to include these data in a course I'm teaching, so did the natural thing of cloning the repo and then quickly trying to import the .csv file. It looks like there are malformed lines, at least according to the `pandas` parser `read_csv()`. I have spent zero time cleaning the dataset-- I was hoping this would work out of the box-- but here is the error:

-------------------------------------

In [1]: import pandas as pd
In [2]: pd.read_csv("egg_database.csv")

ParserError                               Traceback (most recent call last)
<ipython-input-2-43e95e145f2d> in <module>
----> 1 pd.read_csv("egg_database.csv")

~/miniconda3/lib/python3.6/site-packages/pandas/io/parsers.py in parser_f(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, escapechar, comment, encoding, dialect, tupleize_cols, error_bad_lines, warn_bad_lines, skipfooter, doublequote, delim_whitespace, low_memory, memory_map, float_precision)
    676                     skip_blank_lines=skip_blank_lines)
    677
--> 678         return _read(filepath_or_buffer, kwds)
    679
    680     parser_f.__name__ = name

~/miniconda3/lib/python3.6/site-packages/pandas/io/parsers.py in _read(filepath_or_buffer, kwds)
    444
    445     try:
--> 446         data = parser.read(nrows)
    447     finally:
    448         parser.close()

~/miniconda3/lib/python3.6/site-packages/pandas/io/parsers.py in read(self, nrows)
   1034                 raise ValueError('skipfooter not supported for iteration')
   1035
-> 1036         ret = self._engine.read(nrows)
   1037
   1038         # May alter columns / col_dict

~/miniconda3/lib/python3.6/site-packages/pandas/io/parsers.py in read(self, nrows)
   1846     def read(self, nrows=None):
   1847         try:
-> 1848             data = self._reader.read(nrows)
   1849         except StopIteration:
   1850             if self._first_chunk:

pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader.read()

pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader._read_low_memory()

pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader._read_rows()

pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader._tokenize_rows()

pandas/_libs/parsers.pyx in pandas._libs.parsers.raise_parser_error()

ParserError: Error tokenizing data. C error: Expected 19 fields in line 1248, saw 21

---------------------------------

It looks like you have too many fields in that line... is this a known error? I see no issues here on Github

thanks for your help,
Andy

**Comment by shchurch** [comment]
Hi Andy,

I believe the error is because the file is tab delimited, not comma. We have updated the filename to be tsv, not csv. 

Thanks for bringing it to our attention, and let us know if this doesn't solve the problem for you!
Glad you are using the data in the course!

Sam

**Comment by andrewkern** [comment]
thanks Sam. that fixed the issue. I'll close out this issue.
